package com.MBCAF.app.event;

public enum CommonEvent {
    CE_NONE,
    CE_Audio_Play,
    CE_Audio_Stop,
    CE_Image_UploadFaild,
    CE_Image_UploadSucess,
    CE_Session_SetTop,
    CE_Session_RecentListUpdate,
    CE_Session_RecentListSuccess,
    CE_Session_RecentListFail,
    CE_Reconnect_None,
    CE_Reconnect_Success,
    CE_Reconnect_Disable,
    CE_User_InfoOK,
    CE_User_InfoUpdate,
    CE_Login_In,
    CE_Login_OK,
    CE_Login_Fail,
    CE_Login_FailAuth,
    CE_Login_Success,
    CE_Login_Out,
    CE_Login_MsgService,
    CE_Login_PCOnline,
    CE_Login_PCOffline,
    CE_Login_KinckPCSuccess,
    CE_Login_KinckPCFail,
    CE_Connect_MsgServerAddrQ,
    CE_Connect_MsgServerAddrAFail,
    CE_Connect_MsgServerAddrASuccess,
    CE_Connect_MsgServerConnect,
    CE_Connect_MsgServerConnectSuccess,
    CE_Connect_MsgServerConnectFail,
    CE_Connect_MsgServerDisConnect
}
